---
#エンチャント時に消費致します、アイテムを指定致します。
id: "351:4"

#エンチャント時に消費致します、アイテムの個数を指定致します。
count: 3

#エンチャント時に必要なアイテムの不足時に表示致します、アイテムの名前を設定致します...(申し訳ないです...)
displayItemName: ラピスラズリ

#エンチャント時の計算に使用致します、本棚の数を指定致します。(0～15の数字に関しましては、使用可能にてございます...(申し訳ないです...))
bookshelfAmount: 15
...
