---
#エンチャントを実施することは可能なエンチャントを指定致します。
#設定に関しましては、on = 有効,off=無効 と致しましております...(申し訳ないです...)

#ツール、装備全般
耐久(耐久力): "on"

#ブーツ全般
#装備全般
防護(ダメージ軽減): "on"
防火(火炎耐性): "on"
爆発耐性: "on"
間接攻撃耐性(飛び道具耐性): "on"
とげ(棘の鎧): "on"

#ブーツ全般
落下軽減(落下耐性): "on"
水中移動(水中歩行): "on"

#ブーツ全般
水中呼吸: "on"
水中作業(水中採掘): "on"

#剣全般、オノ全般
鋭さ(ダメージ増加): "on"
聖なる力(アンデッド特効): "on"
虫殺し(虫特効): "on"

#剣全般
ノックバック: "on"
火属性: "on"
アイテムボーナス(ドロップ増加): "on"

#つるはし、シャベル、オノ、ハサミ全般
効率(効率強化): "on"

#つるはし、シャベル、オノ全般
シルクタッチ: "on"
幸運: "on"

#弓
パワー(射撃ダメージ増加): "on"
衝撃(パンチ): "on"
火炎(フレイム): "on"
無限: "on"

#釣り竿
宝釣り: "on"
入れ食い: "on"
...
